menu:
    Blog: /
    Gallery: /instagram/
    Archive: /archives/
    GitHub: https://github.com/ivince/
    #Rss: /atom.xml

favicon: /ivince.png
logo: /ivince.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:
ga: #UA-75242174-1

ba: c7b6bef626b02269e3c33389d7c99786

# Copyright Infomation
startyear: 2015
